{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Medidas\",\"dHora_atual\",\"fRelatorio_avancado\",\"Parâmetro1\",\"Transformar o Arquivo de Exemplo\",\"Arquivo de Amostra\",\"Transformar Arquivo\",\"dHora\",\"dDesc\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Parâmetro1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Arquivo de Amostra\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "0994bf42-140e-4f3f-924f-5d8aa76f1cd7",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "    Sheet1_Sheet = Fonte{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data]",
          "in",
          "    Sheet1_Sheet"
        ],
        "kind": "m",
        "lineageTag": "2d1660c7-284e-4bd1-b9a7-5fe9ff8fc9f6",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Arquivo de Amostra",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    dinamico = #\"Atualizaes de Relatrios Gerais\"{[Name=\"dinamico\"]}[Content],",
          "    dinamico1 = dinamico{[Name=\"dinamico\"]}[Content],",
          "    Relatorio_cnt = dinamico1{[Name=\"Relatorio_cnt\"]}[Content],",
          "    Navegação1 = Relatorio_cnt{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "d347f199-cf42-419e-bdc7-f5bc9aa0355b",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Transformar Arquivo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1 as binary) => let",
          "    Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "    Sheet1_Sheet = Fonte{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data]",
          "in",
          "    Sheet1_Sheet",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "5c1409a9-118d-4fa8-b3f8-e92e95e107f8",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transformar o Arquivo de Exemplo\"\"}\" ]",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      }
    ],
    "relationships": [
      {
        "name": "7b01feb4-2152-ef6f-b7f7-07de03a9e3d1",
        "fromColumn": "hora_status",
        "fromTable": "fRelatorio_avancado",
        "toColumn": "Hora",
        "toTable": "dHora"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "31ee79e6-4170-4c22-812b-7e5037b7b22d",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "22ad9989-7813-4bbc-a8d9-ca393d436f10",
        "measures": [
          {
            "name": "nome_usuario_logado",
            "displayFolder": "Cartão de Apresentação",
            "expression": [
              "",
              "",
              "VAR UsuarioCompleto = USERPRINCIPALNAME()",
              "VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH(\"@\", UsuarioCompleto, 1) - 1)",
              "VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, \".\", \" \")",
              "",
              "VAR PalavrasSeparadas = SUBSTITUTE(UsuarioComEspacos, \" \", \"|\")",
              "VAR ListaPalavras = ",
              "    ADDCOLUMNS(",
              "        GENERATESERIES(1, PATHLENGTH(PalavrasSeparadas)),",
              "        \"Palavra\", PATHITEM(PalavrasSeparadas, [Value])",
              "    )",
              "VAR NomeCapitalizado = ",
              "    CONCATENATEX(",
              "        ListaPalavras,",
              "        UPPER(LEFT([Palavra], 1)) & LOWER(MID([Palavra], 2, LEN([Palavra]))),",
              "        \" \"",
              "    )",
              "RETURN NomeCapitalizado"
            ],
            "lineageTag": "5caab57e-4e9c-4c2c-9fd4-b758dc25bc14"
          },
          {
            "name": "data_hora",
            "displayFolder": "Cartão de Apresentação",
            "expression": [
              "",
              "",
              "SELECTEDVALUE(dHora_atual[data])&\" \"&SELECTEDVALUE(dHora_atual[hora])"
            ],
            "lineageTag": "15c705ba-7a58-4ba1-8658-459cedeea47e"
          },
          {
            "name": "qt_movimentada_hoje",
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "fRelatorio_avancado[dt_status_data] = TODAY())",
              "",
              "VAR B = ",
              "IF(A = 0 , 0 , A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "fb4d35b6-090e-4237-b39c-1e1d2c14afbd"
          },
          {
            "name": "qt_movimentada_ontem",
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "fRelatorio_avancado[dt_status_data] = TODAY()-1)",
              "",
              "VAR B = ",
              "IF(A = 0 , 0 , A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "1aad957c-c6c6-4da3-9834-8fa500ce75be"
          },
          {
            "name": "qt_movimentada_semana_passada",
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "fRelatorio_avancado[dt_status_data] = TODAY()-7) ",
              "",
              "VAR B = ",
              "IF(A = 0 , 0 , A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "2bca3234-b323-4b26-a101-f24e32af2704"
          },
          {
            "name": "horas_trabalhadas",
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[hora_status]))"
            ],
            "formatString": "0",
            "lineageTag": "3a3cd2a1-23b7-491b-816a-4f62e43c390f"
          },
          {
            "name": "media_ped_hj",
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[hora_status]),",
              "    fRelatorio_avancado[qt_pcs] > 0,",
              "    fRelatorio_avancado[dt_status_data] = TODAY())",
              "",
              "VAR B =",
              "DIVIDE([qt_movimentada_hoje],A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0.00",
            "lineageTag": "f3aab716-15c3-430e-9bd9-090c4622cd2f"
          },
          {
            "name": "media_ped_ontem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[hora_status]),",
              "    fRelatorio_avancado[qt_pcs] > 0,",
              "    fRelatorio_avancado[dt_status_data] = TODAY()-1)",
              "",
              "VAR B =",
              "DIVIDE([qt_movimentada_ontem],A)",
              "",
              "RETURN",
              "B"
            ],
            "lineageTag": "d353e9fc-6f49-43c1-9d66-109afe3a32f8"
          },
          {
            "name": "media_ped_sem_passada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[hora_status]),",
              "    fRelatorio_avancado[qt_pcs] > 0,",
              "    fRelatorio_avancado[dt_status_data] = TODAY()-7)",
              "",
              "VAR B =",
              "DIVIDE([qt_movimentada_semana_passada],A)",
              "",
              "RETURN",
              "B"
            ],
            "lineageTag": "aac2c01d-6a6a-4131-918d-357261c04889"
          },
          {
            "name": "media_pc_x_ped_hoje",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "DIVIDE([qt_movimentada_hoje],",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "    fRelatorio_avancado[dt_status_data] = TODAY()))",
              "",
              ""
            ],
            "lineageTag": "6ddb14f2-7b47-4765-9161-f6dfcc0622f0"
          },
          {
            "name": "info_dem_hoje",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(dDesc[desc]) = \"Média Acumulado\", [media_ped_hj],",
              "    SELECTEDVALUE(dDesc[desc]) = \"Soma por Hora\" , FORMAT([qt_movimentada_hoje], \"#,0\"),",
              "    SELECTEDVALUE(dDesc[desc]) = \"Peças / Pedidos\", [media_pc_x_ped_hoje])"
            ],
            "lineageTag": "1e3a0708-38d2-4653-8346-5f2df2cb7d2e"
          },
          {
            "name": "media_pc_x_ped_ontem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "DIVIDE([qt_movimentada_ontem],",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "    fRelatorio_avancado[dt_status_data] = TODAY()-1))",
              "",
              ""
            ],
            "lineageTag": "05d2780e-2715-4185-8e78-e035521a9df8"
          },
          {
            "name": "media_pc_x_ped_sem_passada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "DIVIDE([qt_movimentada_semana_passada],",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "    fRelatorio_avancado[dt_status_data] = TODAY()-7))",
              ""
            ],
            "lineageTag": "5196314d-bb1c-40c5-84f8-1bfc314f6d8e"
          },
          {
            "name": "info_dem_ontem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(dDesc[desc]) = \"Média Acumulado\", [media_ped_ontem],",
              "    SELECTEDVALUE(dDesc[desc]) = \"Soma por Hora\" , FORMAT([qt_movimentada_ontem], \"#,0\"),",
              "    SELECTEDVALUE(dDesc[desc]) = \"Peças / Pedidos\", [media_pc_x_ped_ontem])"
            ],
            "lineageTag": "b409be9e-4a56-43c8-bc34-eee5dd5f54b8"
          },
          {
            "name": "info_dem_semana_passada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(dDesc[desc]) = \"Média Acumulado\", [media_ped_sem_passada],",
              "    SELECTEDVALUE(dDesc[desc]) = \"Soma por Hora\" , FORMAT([qt_movimentada_semana_passada], \"#,0\"),",
              "    SELECTEDVALUE(dDesc[desc]) = \"Peças / Pedidos\", [media_pc_x_ped_sem_passada])"
            ],
            "lineageTag": "44b9d857-097f-42dc-8e21-77afb955099d"
          },
          {
            "name": "text_1",
            "displayFolder": "Tabela",
            "expression": "\"JUNDIAÍ - SP\"",
            "lineageTag": "b22fbf5e-79d4-4baf-9f20-11e6d4f73efd"
          },
          {
            "name": "qt_pedidos",
            "displayFolder": "Tabela",
            "expression": [
              "",
              "",
              "DISTINCTCOUNT(fRelatorio_avancado[pedido])"
            ],
            "formatString": "0",
            "lineageTag": "372c42da-808f-429e-9208-12bd718d2ea2"
          },
          {
            "name": "saldo",
            "displayFolder": "Tabela 1",
            "expression": [
              "",
              "",
              "",
              "IF(",
              " [qt_pedidos] = 0 , 0 , [qt_pedidos])"
            ],
            "formatString": "0",
            "lineageTag": "964a056c-7989-455b-b7b7-0e72354a5fd2"
          },
          {
            "name": "vencidos",
            "displayFolder": "Tabela 1",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[status_de_entrega] = \"Vencidos\")",
              "",
              "VAR B = ",
              "IF(A = 0 , 0, A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "7e4e9fa3-d8d2-463a-8136-351b1f5ea5b0"
          },
          {
            "name": "vence_hoje",
            "displayFolder": "Tabela 1",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[status_de_entrega] = \"Vence Hoje\")",
              "",
              "VAR B = ",
              "IF( A = 0 , 0 ,A)",
              "",
              "RETURN ",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "d784e174-3130-46c5-9f8e-65d0f0e4159e"
          },
          {
            "name": ">d+2",
            "displayFolder": "Tabela 1",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[status_de_entrega] = \" >D+2\" || fRelatorio_avancado[status_de_entrega] = \"D+1\")",
              "",
              "VAR B =",
              "IF(A = 0 , 0, A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "8d46d591-40fe-4a49-a6ac-0d2115d9439c"
          },
          {
            "name": "exp_hj",
            "displayFolder": "Tabela 2",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[new_status] = \"EXPEDIDO\",",
              "    fRelatorio_avancado[dt_status_data] = TODAY())"
            ],
            "formatString": "0",
            "lineageTag": "fbb0f078-779f-4397-ac44-1166e43e20c9"
          },
          {
            "name": "saldo_no_exp",
            "displayFolder": "Graf de %",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "IF(",
              " [qt_pedidos] = 0 , 0 , [qt_pedidos]),",
              " fRelatorio_avancado[new_status] <> \"EXPEDIDO\")"
            ],
            "formatString": "0",
            "lineageTag": "4e79024c-8bfe-49fa-ae2b-f623bdb38f5d"
          },
          {
            "name": "vence_hoje_no_exp",
            "displayFolder": "Graf de %",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[status_de_entrega] = \"Vence Hoje\",",
              "    fRelatorio_avancado[new_status] <> \"EXPEDIDO\")",
              "",
              "VAR B = ",
              "IF( A = 0 , 0 ,A)",
              "",
              "RETURN ",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "1c791b32-6cda-4903-b607-858e30edac28"
          },
          {
            "name": "vencidos_no_exp",
            "displayFolder": "Graf de %",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[status_de_entrega] = \"Vencidos\",",
              "    fRelatorio_avancado[new_status] <> \"EXPEDIDO\")",
              "",
              "VAR B = ",
              "IF(A = 0 , 0, A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "82f76f20-a705-4078-9cb6-2038fa3795b1"
          },
          {
            "name": "liberado_sep",
            "displayFolder": "Tabela 2",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[new_status] = \"LIBERADO SEPARAÇÃO\")",
              "",
              "VAR B = ",
              "IF( A = 0 , 0 , A )",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "44ffba1d-79f8-4f1f-8615-7e89ccb7b688"
          },
          {
            "name": "fim_sep",
            "displayFolder": "Tabela 2",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[new_status] = \"FIM SEPARAÇÃO\")",
              "",
              "VAR B = ",
              "IF( A = 0 , 0 , A )",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "76c4e6fb-699a-4a5f-8472-0ca6bb6a16a3"
          },
          {
            "name": "faturado",
            "displayFolder": "Tabela 2",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[new_status] = \"FATURADO\")",
              "",
              "VAR B = ",
              "IF( A = 0 , 0 , A )",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "8c1ec150-3c66-42cb-a9cf-8828bc1cb3de"
          },
          {
            "name": "saldo_cliente_status",
            "displayFolder": "Tabela 2",
            "expression": [
              "",
              "",
              "[exp_hj] + [fim_sep] + [liberado_sep] + [faturado]"
            ],
            "formatString": "0",
            "lineageTag": "84064535-3b36-466d-994e-11972ee7bcce"
          },
          {
            "name": "faturamento_%",
            "displayFolder": "Graf de %",
            "expression": [
              "",
              "",
              "DIVIDE([faturado],[saldo_no_exp]+[faturado])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "49752b20-715f-49fa-a6af-081df66c7ed3"
          },
          {
            "name": "sep_%",
            "displayFolder": "Graf de %",
            "expression": [
              "",
              "",
              "DIVIDE([fim_sep]+[liberado_sep],[saldo_no_exp]+[fim_sep]+[liberado_sep])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a93aa222-bca2-4102-a3af-bf77a2d67b91"
          },
          {
            "name": "media_pcs_dia",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[dt_status_data]),",
              "    ALL(fRelatorio_avancado))",
              "",
              "VAR B = ",
              "",
              "DIVIDE(SUM(fRelatorio_avancado[qt_pcs]),A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "e30a19a5-8c24-4a5b-bb04-bdc867eaa269"
          },
          {
            "name": "media_pd_dia",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[dt_status_data]),",
              "    ALL(fRelatorio_avancado))",
              "",
              "VAR B = ",
              "",
              "DIVIDE(DISTINCTCOUNT(fRelatorio_avancado[pedido]),A)",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0",
            "lineageTag": "353ea476-2c52-49b3-80b4-5869fae23733"
          },
          {
            "name": "media_pcs/ped",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "[media_pcs_dia]/[media_pd_dia]"
            ],
            "lineageTag": "c626f06d-5523-41d3-9d31-63f204ebf771"
          },
          {
            "name": "comp_media_pcs",
            "expression": [
              "",
              "",
              "VAR A = ",
              "DIVIDE([pcs_hoje],[media_pcs_dia]) - 1",
              "",
              "VAR B = ",
              "SWITCH(",
              "    TRUE(),",
              "    A > 0 , \"⬆️ \"&FORMAT(A, \"0%\"),",
              "    A < 0 , \"⬇️ \"&FORMAT(A, \"0%\"),A)",
              "",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e2bb779f-a892-476a-b4f7-448c2df5f7cc"
          },
          {
            "name": "seq",
            "expression": [
              "",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(fRelatorio_avancado[new_status]) = \"LIBERADO SEPARAÇÃO\", 1 ,",
              "    SELECTEDVALUE(fRelatorio_avancado[new_status]) = \"FIM SEPARAÇÃO\", 2 ,",
              "    SELECTEDVALUE(fRelatorio_avancado[new_status]) = \"FATURADO\", 3 , 0 )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "15906d8a-62ce-448a-9d12-287561066c15"
          },
          {
            "name": "pcs_hoje",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "    SUM(fRelatorio_avancado[qt_pcs]),",
              "    fRelatorio_avancado[dt_status_data] = TODAY())",
              "",
              "",
              "RETURN",
              "",
              "A"
            ],
            "formatString": "0",
            "lineageTag": "a9d5458d-4da3-4e99-b369-79811e05e5fe"
          },
          {
            "name": "ped_hoje",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "    DISTINCTCOUNT(fRelatorio_avancado[pedido]),",
              "    fRelatorio_avancado[dt_status_data] = TODAY())",
              "",
              "RETURN",
              "A",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9a618504-6760-4f92-ba49-c8cd13a357b0"
          },
          {
            "name": "comp_media_ped",
            "expression": [
              "",
              "",
              "VAR A = ",
              "DIVIDE([ped_hoje],[media_pd_dia]) - 1",
              "",
              "VAR B = ",
              "SWITCH(",
              "    TRUE(),",
              "    A > 0 , \"⬆️ \"&FORMAT(A, \"0%\"),",
              "    A < 0 , \"⬇️ \"&FORMAT(A, \"0%\"),A)",
              "",
              "",
              "RETURN",
              "B"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2a5265ca-79eb-49f7-86e5-32f20f8bbba2"
          },
          {
            "name": "comp_media_pedxpcs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR A = ",
              "DIVIDE([media_pc_x_ped_hoje],[media_pcs/ped]) - 1",
              "",
              "VAR B = ",
              "SWITCH(",
              "    TRUE(),",
              "    A > 0 , \"⬆️ \"&FORMAT(A, \"0%\"),",
              "    A < 0 , \"⬇️ \"&FORMAT(A, \"0%\"),A)",
              "",
              "",
              "RETURN",
              "B"
            ],
            "lineageTag": "d352203f-50e0-4e7a-b25e-bb3413e5907f"
          },
          {
            "name": "duracao_6",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[duracao] = \"6+\")"
            ],
            "formatString": "0",
            "lineageTag": "0b0b02bc-9efd-482e-bdf5-6d1f1c59166d"
          },
          {
            "name": "duracao_12",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[duracao] = \"12+\")"
            ],
            "formatString": "0",
            "lineageTag": "bf33d12e-7996-4c77-8280-77e4d59d7654"
          },
          {
            "name": "duracao_24",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [qt_pedidos],",
              "    fRelatorio_avancado[duracao] = \"24+\")"
            ],
            "formatString": "0",
            "lineageTag": "cdd2def0-325f-4c62-9cf6-33af5567bd8f"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHora_atual",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "03f50b42-4c15-4803-9527-15973da7dcad",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "2ea294b5-f32f-43c3-913b-9d9050f5d910",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bc0865e8-d5d5-483a-9a72-18cdcbbd9540",
        "partitions": [
          {
            "name": "dHora_atual",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = DateTime.From(DateTime.LocalNow()) - #duration(0, 3, 0, 0),",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"hora\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"hora\", type datetime}}),",
                "  #\"Hora inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Hora (2)\", each DateTime.Time([hora]), type nullable time),",
                "  #\"Data calculada\" = Table.TransformColumns(#\"Hora inserida\", {{\"hora\", each DateTime.Date(_), type nullable date}}),",
                "  #\"Colunas renomeadas 1\" = Table.RenameColumns(#\"Data calculada\", {{\"hora\", \"data\"}, {\"Hora (2)\", \"hora\"}})",
                "in",
                "    #\"Colunas renomeadas 1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fRelatorio_avancado",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cliente_fantasma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a153363-9045-4594-bc9b-9521d9599517",
            "sourceColumn": "cliente_fantasma",
            "summarizeBy": "none"
          },
          {
            "name": "pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51c49f03-4af4-4148-bf4e-5003859f2162",
            "sourceColumn": "pedido",
            "summarizeBy": "none"
          },
          {
            "name": "qt_pcs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "beda866c-0420-41c1-b37c-b01be2a7ee60",
            "sourceColumn": "qt_pcs",
            "summarizeBy": "sum"
          },
          {
            "name": "tranps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a8c2e4b-4b59-4e4e-b8c5-b71bd4ce5102",
            "sourceColumn": "tranps",
            "summarizeBy": "none"
          },
          {
            "name": "dt_gravacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "59e6fd89-63cc-4645-a980-37a4ba8c9f89",
            "sourceColumn": "dt_gravacao",
            "summarizeBy": "none"
          },
          {
            "name": "dt_limite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "3b426f3c-844b-4fe0-a949-fdf76db9ff29",
            "sourceColumn": "dt_limite",
            "summarizeBy": "none"
          },
          {
            "name": "status_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5e02d64-c7b2-4a43-a0fd-934e490630dc",
            "sourceColumn": "status_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "dt_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ada71a55-e3fa-4a0c-bb12-e74a085cb7dc",
            "sourceColumn": "dt_status",
            "summarizeBy": "none"
          },
          {
            "name": "nota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a580215e-a72e-4eff-b937-e7858d440f25",
            "sourceColumn": "nota",
            "summarizeBy": "sum"
          },
          {
            "name": "list_sep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e12416af-eb59-4134-8416-234ea4b2c09c",
            "sourceColumn": "list_sep",
            "summarizeBy": "sum"
          },
          {
            "name": "t_nota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "df72dfe4-4903-451f-8b0d-9fd336c67943",
            "sourceColumn": "t_nota",
            "summarizeBy": "sum"
          },
          {
            "name": "cd_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce2b1d54-af98-4a87-8f9e-e224487cf5fa",
            "sourceColumn": "cd_pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "romaneio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "924e3500-7ead-46f8-b1dc-7bfd128fa356",
            "sourceColumn": "romaneio",
            "summarizeBy": "sum"
          },
          {
            "name": "rastreio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00fab123-0136-4238-8262-4cb8b20ebffb",
            "sourceColumn": "rastreio",
            "summarizeBy": "none"
          },
          {
            "name": "new_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7817c65b-0f55-4ff7-8484-71f4b42263fd",
            "sourceColumn": "new_status",
            "summarizeBy": "none"
          },
          {
            "name": "dt_status_data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "174538ae-9514-4341-8798-496f14501841",
            "sourceColumn": "dt_status_data",
            "summarizeBy": "none"
          },
          {
            "name": "hora_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Time",
            "lineageTag": "e97f3933-2758-4947-8a40-48c0f993ddbb",
            "sourceColumn": "hora_status",
            "summarizeBy": "none"
          },
          {
            "name": "duracao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04867468-a0c6-4428-9c3d-d1829c29f3da",
            "sourceColumn": "duracao",
            "summarizeBy": "none"
          },
          {
            "name": "status_de_entrega",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "353250a8-2904-4dd8-bf46-97875ce58afb",
            "sourceColumn": "status_de_entrega",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "610434fc-dd07-40ca-88f9-3c633ebc7219",
        "partitions": [
          {
            "name": "fRelatorio_avancado",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    dinamico = #\"Atualizaes de Relatrios Gerais\"{[Name=\"dinamico\"]}[Content],",
                "    dinamico1 = dinamico{[Name=\"dinamico\"]}[Content],",
                "    Relatorio_cnt = dinamico1{[Name=\"Relatorio_cnt\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(Relatorio_cnt, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo\", each #\"Transformar Arquivo\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo\", Table.ColumnNames(#\"Transformar Arquivo\"(#\"Arquivo de Amostra\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Nome da Origem\", \"Column1\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Colunas Removidas\", each [Column3] <> null and [Column3] <> \"\"),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas Filtradas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"CLIENTE FANTASIA\", type text}, {\"PEDIDO\", type text}, {\"TOTAL ITENS\", Int64.Type}, {\"TRASPORTADORA\", type text}, {\"DATA DE GRAVACAO\", type datetime}, {\"DATA LIMITE\", type date}, {\"STATUS\", type text}, {\"DATA STATUS\", type datetime}, {\"NOTA FISCAL\", Int64.Type}, {\"LISTA SEPARACAO\", Int64.Type}, {\"TOTAL NOTA\", Int64.Type}, {\"CODIGO PEDIDO\", Int64.Type}, {\"ROMANEIO\", Int64.Type}, {\"RASTREIO\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"CLIENTE FANTASIA\", \"cliente_fantasma\"}, {\"PEDIDO\", \"pedido\"}, {\"TOTAL ITENS\", \"qt_pcs\"}, {\"TRASPORTADORA\", \"tranps\"}, {\"DATA DE GRAVACAO\", \"dt_gravacao\"}, {\"DATA LIMITE\", \"dt_limite\"}, {\"STATUS\", \"status_pedido\"}, {\"DATA STATUS\", \"dt_status\"}, {\"NOTA FISCAL\", \"nota\"}, {\"LISTA SEPARACAO\", \"list_sep\"}, {\"TOTAL NOTA\", \"t_nota\"}, {\"CODIGO PEDIDO\", \"cd_pedido\"}, {\"ROMANEIO\", \"romaneio\"}, {\"RASTREIO\", \"rastreio\"}}),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Colunas Renomeadas\", {{\"dt_limite\", null}}),",
                "    new_status = Table.AddColumn(#\"Erros Substituídos\", \"new_status\", each if List.Contains({\"AGUARDANDO ENTRADA\", \"SEM ESTOQUE\", \"ESTOQUE PULMAO\", \"LIBERADO PARA SEPARACAO\"},[status_pedido]) then \"LIBERADO SEPARAÇÃO\" ",
                "",
                "else if List.Contains({\"AGUARDANDO NOTA FISCAL\", \"AGUARDANDO REIMPRESSAO DE NOTA FISCAL\", \"AGUARDANDO ETIQUETA\", \"AGUARDANDO REIMPRESSAO DE ETIQUETA\", \"CANCELAMENTO SOLICITADO\", \"AGUARDANDO CANCELAMENTO\", \"AGUARDANDO EXPEDICAO\", \"AGUARDANDO EXPEDICAO(ENVIADO PARA ANALISE)\", \"EM EXPEDICAO\"},[status_pedido]) then ",
                "\"FATURADO\" ",
                "",
                "else if List.Contains({\"AGUARDANDO PACKING\", \"AGUARDANDO PACKING(ENVIANDO PARA ANALISE)\"},[status_pedido]) then \"FIM SEPARAÇÃO\"",
                "",
                "else if [status_pedido] = \"EXPEDIDO\" then \"EXPEDIDO\"",
                "",
                "else if [status_pedido] = \"AGUARDANDO PICKING\" then \"EM SEPARAÇÃO\"",
                "",
                "else if List.Contains({\"REVERSA EM TRATAMENTO\",\"CANCELADO\"},[status_pedido])  then \"excluir_da_base\"",
                "",
                "else \"ig\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(new_status,{{\"new_status\", type text}}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado2\", each ([new_status] <> \"excluir_da_base\")),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Linhas Filtradas1\", \"dt_status\", \"dt_status - Copiar\"),",
                "    #\"Início da Hora Inserido\" = Table.AddColumn(#\"Coluna Duplicada\", \"Início da Hora\", each Time.StartOfHour([#\"dt_status - Copiar\"]), type datetime),",
                "    #\"Data Extraída\" = Table.TransformColumns(#\"Início da Hora Inserido\",{{\"dt_status - Copiar\", DateTime.Date, type date}}),",
                "    #\"Horário Extraído\" = Table.TransformColumns(#\"Data Extraída\",{{\"Início da Hora\", DateTime.Time, type time}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Horário Extraído\",{{\"dt_status - Copiar\", \"dt_status_data\"}, {\"Início da Hora\", \"hora_status\"}}),",
                "    duracao = Table.AddColumn(#\"Colunas Renomeadas2\", \"duracao\", each let",
                "    dt_atual = DateTime.LocalNow(),  ",
                "    dif_horas = Duration.TotalHours(dt_atual - [dt_status]), ",
                "    resultado = ",
                "        if dif_horas >= 24 then \"24+\"",
                "        else if dif_horas >= 12 then \"12+\"",
                "        else if dif_horas >= 6 then \"6+\"",
                "        else \"Menos de 6h\"",
                "in",
                "    resultado),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(duracao,{{\"duracao\", type text}}),",
                "    status_de_entrega = Table.AddColumn(#\"Tipo Alterado3\", \"status_de_entrega\", each let Hoje = Date.From(DateTime.LocalNow() - #duration(0, 3, 0, 0)) in",
                "",
                "// Tratamento para sexta-feira",
                "if Date.DayOfWeek(Hoje) = 5 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 3) then \"D+1\"",
                "else if Date.DayOfWeek(Hoje) = 5 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 4) then \"D+2\"",
                "else if Date.DayOfWeek(Hoje) = 5 and (Duration.Days(Date.From([dt_limite]) - Hoje) > 4) then \" >D+2\"",
                "",
                "// Tratamento para sábado",
                "else if Date.DayOfWeek(Hoje) = 6 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 2) then \"Vence Segunda\"",
                "else if Date.DayOfWeek(Hoje) = 6 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 3) then \"D+1\"",
                "else if Date.DayOfWeek(Hoje) = 6 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 4) then \"D+2\"",
                "else if Date.DayOfWeek(Hoje) = 6 and (Duration.Days(Date.From([dt_limite]) - Hoje) > 4) then \" >D+2\"",
                "",
                "// Tratamento para domingo",
                "else if Date.DayOfWeek(Hoje) = 0 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 1) then \"Vence Segunda\"",
                "else if Date.DayOfWeek(Hoje) = 0 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 2) then \"D+1\"",
                "else if Date.DayOfWeek(Hoje) = 0 and (Duration.Days(Date.From([dt_limite]) - Hoje) = 3) then \"D+2\"",
                "else if Date.DayOfWeek(Hoje) = 0 and (Duration.Days(Date.From([dt_limite]) - Hoje) > 3) then \" >D+2\"",
                "",
                "// Tratamento para dias da semana",
                "else if Date.From([dt_limite]) < Hoje then \"Vencidos\"",
                "else if Duration.Days(Date.From([dt_limite]) - Hoje) = 0 then \"Vence Hoje\"",
                "else if Duration.Days(Date.From([dt_limite]) - Hoje) = 1 then \"D+1\"",
                "else if Duration.Days(Date.From([dt_limite]) - Hoje) = 2 then \"D+2\"",
                "else if Duration.Days(Date.From([dt_limite]) - Hoje) > 2 then \" >D+2\"",
                "",
                "// Tratamento para casos não previstos",
                "else \"tratar sobra\"),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(status_de_entrega,{{\"status_de_entrega\", type text}})",
                "in",
                "    #\"Tipo Alterado4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dHora",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "74ef5e58-5ac7-4425-b9f4-290ab08fbe1c",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "7eeeb4f6-0f74-4258-a48d-0f228d2c7dd5",
        "partitions": [
          {
            "name": "dHora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Pc25DYAwFAXBXhwT/H1grlYs998GSIjNJpsxWtVd1ebyChW1qk11tatDner6hQceeOCBBx544IEHHvGIRzzyHfMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Hora = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Hora\", type time}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dDesc",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a185af5-b6c4-4ddb-932f-21d48b9d3849",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "n",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67a13cf9-d7e1-4b0f-805d-e4992e397627",
            "sourceColumn": "n",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "753b4e8e-1bc3-44c2-b463-bb7415776a56",
        "partitions": [
          {
            "name": "dDesc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8j28MiUzUcExuTS3NCcxJV9JR8lQKVYnWik4PzdRoSC/SMEjvygRKGoEFg1IPbw8sVhBXyEgNSUzJb8YKGGsFBsLAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [desc = _t, n = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"desc\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}